import { CaseAnalysis } from '@/types/legal';

export const exportToPDF = (analysis: CaseAnalysis): void => {
  const content = generatePDFContent(analysis);
  
  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }
  
  printWindow.document.write(content);
  printWindow.document.close();
  
  // Wait for content to load then print
  printWindow.onload = () => {
    printWindow.print();
  };
};

const generatePDFContent = (analysis: CaseAnalysis): string => {
  const date = new Date(analysis.timestamp).toLocaleString('en-IN', {
    dateStyle: 'full',
    timeStyle: 'short',
  });

  return `
<!DOCTYPE html>
<html>
<head>
  <title>Legal Case Analysis - ${analysis.classification.primaryDomain}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&family=Source+Sans+Pro:wght@400;600&display=swap');
    
    * { margin: 0; padding: 0; box-sizing: border-box; }
    
    body {
      font-family: 'Source Sans Pro', sans-serif;
      line-height: 1.6;
      color: #1a2332;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    
    h1, h2, h3 { font-family: 'Merriweather', serif; }
    
    .header {
      text-align: center;
      border-bottom: 3px double #c9a227;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    
    .header h1 {
      color: #1a2840;
      font-size: 24px;
      margin-bottom: 10px;
    }
    
    .header .date {
      color: #666;
      font-size: 14px;
    }
    
    .disclaimer {
      background: #fff3cd;
      border: 1px solid #c9a227;
      padding: 15px;
      margin-bottom: 30px;
      font-size: 12px;
      text-align: center;
    }
    
    .section {
      margin-bottom: 25px;
      page-break-inside: avoid;
    }
    
    .section h2 {
      color: #1a2840;
      font-size: 16px;
      border-bottom: 1px solid #c9a227;
      padding-bottom: 8px;
      margin-bottom: 15px;
    }
    
    .section h3 {
      font-size: 14px;
      color: #333;
      margin: 10px 0 5px;
    }
    
    .classification-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
    }
    
    .stat-box {
      background: #f8f6f0;
      padding: 12px;
      border-left: 3px solid #c9a227;
    }
    
    .stat-label {
      font-size: 11px;
      color: #666;
      text-transform: uppercase;
    }
    
    .stat-value {
      font-size: 14px;
      font-weight: 600;
      color: #1a2840;
    }
    
    ul {
      padding-left: 20px;
      margin: 10px 0;
    }
    
    li {
      margin: 5px 0;
      font-size: 13px;
    }
    
    .risk-indicator {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 4px;
      font-weight: 600;
      font-size: 12px;
    }
    
    .risk-low { background: #d4edda; color: #155724; }
    .risk-medium { background: #fff3cd; color: #856404; }
    .risk-high { background: #f8d7da; color: #721c24; }
    
    .limitation-safe { color: #155724; }
    .limitation-borderline { color: #856404; }
    .limitation-timebarred { color: #721c24; }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      text-align: center;
      font-size: 11px;
      color: #666;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 10px 0;
      font-size: 12px;
    }
    
    th, td {
      padding: 8px;
      text-align: left;
      border: 1px solid #ddd;
    }
    
    th {
      background: #f8f6f0;
      font-weight: 600;
    }
    
    @media print {
      body { padding: 20px; }
      .section { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Indian Legal Case Analysis Report</h1>
    <div class="date">Generated: ${date}</div>
  </div>
  
  <div class="disclaimer">
    <strong>DISCLAIMER:</strong> This analysis is generated by AI for educational and research purposes only. 
    It does not constitute legal advice. Please consult a qualified legal professional for actual legal matters.
  </div>
  
  <div class="section">
    <h2>Case Classification</h2>
    <div class="classification-grid">
      <div class="stat-box">
        <div class="stat-label">Primary Domain</div>
        <div class="stat-value">${analysis.classification.primaryDomain}</div>
      </div>
      <div class="stat-box">
        <div class="stat-label">Procedural Stage</div>
        <div class="stat-value">${analysis.classification.proceduralStage}</div>
      </div>
      <div class="stat-box">
        <div class="stat-label">Complexity Score</div>
        <div class="stat-value">${(analysis.classification.complexityScore * 100).toFixed(0)}%</div>
      </div>
      <div class="stat-box">
        <div class="stat-label">Confidence</div>
        <div class="stat-value">${(analysis.classification.confidenceScore * 100).toFixed(0)}%</div>
      </div>
    </div>
    ${analysis.classification.secondaryDomains.length > 0 ? `
    <h3>Secondary Domains</h3>
    <p>${analysis.classification.secondaryDomains.join(', ')}</p>
    ` : ''}
  </div>
  
  <div class="section">
    <h2>Legal Provisions</h2>
    <h3>Core Section</h3>
    <p>${analysis.legalProvisions.coreSection}</p>
    ${analysis.legalProvisions.applicableSections.length > 0 ? `
    <h3>Applicable Sections</h3>
    <ul>${analysis.legalProvisions.applicableSections.map(s => `<li>${s}</li>`).join('')}</ul>
    ` : ''}
    ${analysis.legalProvisions.misusedSections.length > 0 ? `
    <h3>Potentially Misused Sections</h3>
    <ul>${analysis.legalProvisions.misusedSections.map(s => `<li>${s}</li>`).join('')}</ul>
    ` : ''}
    ${analysis.legalProvisions.constitutionalAngles.length > 0 ? `
    <h3>Constitutional Angles</h3>
    <ul>${analysis.legalProvisions.constitutionalAngles.map(s => `<li>${s}</li>`).join('')}</ul>
    ` : ''}
  </div>
  
  <div class="section">
    <h2>Facts & Evidence Assessment</h2>
    <p><strong>Evidence Strength:</strong> ${analysis.factEvidence.evidenceStrength}</p>
    <h3>Key Facts</h3>
    <ul>${analysis.factEvidence.keyFacts.map(f => `<li>${f}</li>`).join('')}</ul>
    ${analysis.factEvidence.courtRequirements.length > 0 ? `
    <h3>Court Requirements</h3>
    <ul>${analysis.factEvidence.courtRequirements.map(r => `<li>${r}</li>`).join('')}</ul>
    ` : ''}
    ${analysis.factEvidence.gaps.length > 0 ? `
    <h3>Evidence Gaps</h3>
    <ul>${analysis.factEvidence.gaps.map(g => `<li>${g}</li>`).join('')}</ul>
    ` : ''}
  </div>
  
  <div class="section">
    <h2>Jurisdiction & Limitation</h2>
    <p><strong>Correct Forum:</strong> ${analysis.jurisdiction.correctForum}</p>
    <p><strong>Limitation Status:</strong> 
      <span class="limitation-${analysis.jurisdiction.limitationStatus.toLowerCase().replace('-', '')}">${analysis.jurisdiction.limitationStatus}</span>
    </p>
    <p>${analysis.jurisdiction.limitationDetails}</p>
    ${analysis.jurisdiction.alternativeForums.length > 0 ? `
    <h3>Alternative Forums</h3>
    <ul>${analysis.jurisdiction.alternativeForums.map(f => `<li>${f}</li>`).join('')}</ul>
    ` : ''}
  </div>
  
  <div class="section">
    <h2>Procedural Path</h2>
    <p><strong>Total Timeline:</strong> ${analysis.proceduralPath.totalTimeline}</p>
    <table>
      <thead>
        <tr><th>Step</th><th>Timeline</th><th>Notes</th></tr>
      </thead>
      <tbody>
        ${analysis.proceduralPath.steps.map(s => `<tr><td>${s.step}</td><td>${s.timeline}</td><td>${s.notes}</td></tr>`).join('')}
      </tbody>
    </table>
    ${analysis.proceduralPath.urgentActions.length > 0 ? `
    <h3>Urgent Actions</h3>
    <ul>${analysis.proceduralPath.urgentActions.map(a => `<li>${a}</li>`).join('')}</ul>
    ` : ''}
  </div>
  
  <div class="section">
    <h2>Risk & Outcome Analysis</h2>
    <p><strong>Success Probability:</strong> 
      <span class="risk-indicator risk-${analysis.riskOutcome.successProbability.toLowerCase()}">${analysis.riskOutcome.successProbability}</span>
    </p>
    ${analysis.riskOutcome.strengthFactors.length > 0 ? `
    <h3>Strength Factors</h3>
    <ul>${analysis.riskOutcome.strengthFactors.map(f => `<li>${f}</li>`).join('')}</ul>
    ` : ''}
    ${analysis.riskOutcome.riskFactors.length > 0 ? `
    <h3>Risk Factors</h3>
    <ul>${analysis.riskOutcome.riskFactors.map(f => `<li>${f}</li>`).join('')}</ul>
    ` : ''}
    ${analysis.riskOutcome.tacticalConsiderations.length > 0 ? `
    <h3>Tactical Considerations</h3>
    <ul>${analysis.riskOutcome.tacticalConsiderations.map(t => `<li>${t}</li>`).join('')}</ul>
    ` : ''}
  </div>
  
  <div class="section">
    <h2>Precedents & Judicial Position</h2>
    <p><strong>Judicial Attitude:</strong> ${analysis.precedents.judicialAttitude}</p>
    ${analysis.precedents.settledPrinciples.length > 0 ? `
    <h3>Settled Principles</h3>
    <ul>${analysis.precedents.settledPrinciples.map(p => `<li>${p}</li>`).join('')}</ul>
    ` : ''}
    ${analysis.precedents.relevantCases.length > 0 ? `
    <h3>Relevant Cases</h3>
    <table>
      <thead>
        <tr><th>Case</th><th>Citation</th><th>Relevance</th></tr>
      </thead>
      <tbody>
        ${analysis.precedents.relevantCases.map(c => `<tr><td>${c.name}</td><td>${c.citation}</td><td>${c.relevance}</td></tr>`).join('')}
      </tbody>
    </table>
    ` : ''}
  </div>
  
  <div class="footer">
    <p>This report was generated by the Indian Legal Case Analysis System</p>
    <p>For educational and research purposes only - Not legal advice</p>
  </div>
</body>
</html>
  `;
};
